version: '3.9'
name: tp1
services:
      
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - infra_testing_net
    volumes:
      - ./server/config.ini:/config.ini
      - ./middleware/middleware_config.ini:/middleware_config.ini
  
  result_reducer:
    container_name: result_reducer
    image: result_reducer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - infra_testing_net
    volumes:
      - ./result_reducer/config.ini:/config.ini
      - ./middleware/middleware_config.ini:/middleware_config.ini

  worker_stations1:
    container_name: worker_stations1
    image: station_worker:latest
    entrypoint: python3 /main.py
    networks:
      - infra_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1
      - LOGGING_LEVEL=INFO

  worker_stations2:
    container_name: worker_stations2
    image: station_worker:latest
    entrypoint: python3 /main.py
    networks:
      - infra_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2
      - LOGGING_LEVEL=INFO

  worker_weather1:
    container_name: worker_weather1
    image: weather_worker:latest
    entrypoint: python3 /main.py
    networks:
      - infra_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3
      - LOGGING_LEVEL=INFO

  worker_weather2:
    container_name: worker_weather2
    image: weather_worker:latest
    entrypoint: python3 /main.py
    networks:
      - infra_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=4
      - LOGGING_LEVEL=INFO

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - infra_testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./middleware/middleware_config.ini:/middleware_config.ini
      - ./data/:/data

networks:
  infra_testing_net:
    external: true
