version: '3.9'
name: infra
services:

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    networks:
      - testing_net
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24