version: '3.9'
name: tp0
services:

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
      
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    volumes:
      - ./server/config.ini:/config.ini

  worker1:
  build:
    context: ./worker
    dockerfile: worker.dockerfile
  depends_on:
    - rabbitmq
  links: 
    - rabbitmq
  environment:
    - PYTHONUNBUFFERED=1
    - WORKER_ID=1

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/:/data

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
