version: '3.9'
name: tp1
services:
      
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - infra_testing_net
    volumes:
      - ./server/config.ini:/config.ini

  worker1:
    container_name: worker1
    image: worker:latest
    entrypoint: python3 /main.py
    depends_on:
      - server
    networks:
      - infra_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1
      - LOGGING_LEVEL=INFO

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - infra_testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/:/data

networks:
  infra_testing_net:
    external: true
